# Generated by Django 3.1.5 on 2021-02-09 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField(default='09.02.2021 07:14')),
                ('status', models.CharField(choices=[('Completed', 'completed'), ('In progress', 'in progress'), ('Planned', 'Planned')], default='In progress', max_length=15)),
                ('author', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
    ]
