# Generated by Django 3.1.5 on 2021-01-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Completed', 'completed'), ('In progress', 'in progress'), ('Planned', 'Planned')], default='In progress', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default='24.01.2021 10:31'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default='24.01.2021 10:31'),
        ),
    ]
