# Generated by Django 3.1.5 on 2021-02-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210209_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(default='10.02.2021 08:42'),
        ),
    ]
